# Mobs Drop Heads Configuration
#
# Enabled Mobs
#
Skeleton: true
Zombie: true
Creeper: true
Wither Skeleton: false
Player: true
#
# Drop chance is a percentage
# For example, "Skeleton Drop Chance: 50" would be a 50% drop chance.
#
Skeleton Drop Chance: 10
Zombie Drop Chance: 10
Creeper Drop Chance: 10
Wither Skeleton Drop Chance: 4
Player Drop Chance: 100
#
# Mobs have to be killed with a stone, iron, gold, or diamond sword to drop their head
#
Heads Require Swords: true