# Mobs Drop Heads Configuration
#
# Enabled Mobs
#
Skeleton: true
Zombie: true
Creeper: true
Blaze: true
Cave Spider: true
Chicken: true
Cow: true
Enderman: true
Ghast: true
Magma Cube: true
Mooshroom: true
Pig: true
Ocelot: true
Zombie Pigman: true
Sheep: true
Slime: true
Spider: true
Squid: true
Villager: true
Iron Golem: true
Wither Skeleton: false
Player: true
#
# Drop chance is a percentage
# For example, "Skeleton Drop Chance: 50" would be a 50% drop chance.
#
Skeleton Drop Chance: 10
Zombie Drop Chance: 10
Creeper Drop Chance: 10
Blaze Drop Chance: 15
Cave Spider Drop Chance: 10
Chicken Drop Chance: 5
Cow Drop Chance: 10
Enderman Drop Chance: 10
Ghast Drop Chance: 100
Magma Cube Drop Chance: 10
Mooshroom Drop Chance: 10
Ocelot Drop Chance: 10
Pig Drop Chance: 10
Zombie Pigman Drop Chance: 10
Sheep Drop Chance: 10
Slime Drop Chance: 10
Spider Drop Chance: 10
Squid Drop Chance: 20
Villager Drop Chance: 25
Iron Golem Drop Chance: 100
Wither Skeleton Drop Chance: 5
Player Drop Chance: 100
#
# A mob must be killed with a specific item in order for them to drop their head.
# Separate items using ","
# Example: "Killed Using: DIAMOND_SWORD,DIRT" will require the living entity to be killed with a Diamond Sword or a dirt block in the player's hand.
#
Requires Item: true
Killed Using: STONE_SWORD,IRON_SWORD,GOLD_SWORD,DIAMOND_SWORD
#
# Should a head still have a chance of dropping even if the mob isn't killed by a player?
#
Ignore Killer: false